
# format 

apps: 
  bind9: 
    values:
      mount_configuration_from_secret:
        enabled: true
        secretName: dns-zone-base
  external-dns: 
    values:
      mount_configuration_from_secret:
        enabled: false
        secretName: dns-zone-base
        anotherSecretName: dns-zone-base
