
# format 

# apps: 
#   <appname>:
#     secretName: optional-overide-name
#     values: # this is what is used to create the secret
#       some-item: 
#         some-other-item: "new-value"

apps: 
  bind9: 
    values:
      mount_configuration_from_secret:
        enabled: true
        secretName: dns-zone-base
  bind10: 
    values:
      mount_configuration_from_secret:
        enabled: false
        secretName: dns-zone-base
        anotherSecretName: dns-zone-base
