# for each app make a secret

{{- range $name, $config := .Values.apps }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}-values
  annotations: {}
  labels: {}
data:
  values.yaml: {{ $config | toYaml | b64enc }}
{{- end }}