name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: 'json'
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"

      # - name: Run classic chart-releaser
      #   uses: helm/chart-releaser-action@v1.6.0
      #   with:
      #     skip_existing: true
      #   env:
      #     CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
      
      - name: Helm OCI Charts Releaser
        id: oci_release
        uses: niich/helm-oci-charts-releaser@v0.1.3-r2
        with:
            oci_registry: ghcr.io/niich/charts
            oci_username: niich
            oci_password: ${{ secrets.ACTIONS_TOKEN }}
            github_token: ${{ secrets.ACTIONS_TOKEN }}
            # tag_name_pattern: "{chartName}-chart"
            skip_existing: false
      
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: ${{ job.status }}
          username: "GitHub Bot"
          message: "New charts have been pushed.\n\n${{join(steps.oci_release.outputs.released_charts, '\n')}}"
